---
title: "Covid Project Group 3 Exploration 3: Counts and Rates by Continent"
author: "Kaitlyn Won, Jyoti Michael D Rozario, BaoLong Nguyen"
output:
  html_document:
    number_sections: yes
    toc: yes  
  pdf_document:
    toc: yes
---
# Data Processing

# Data Visualization: Total Confirmed Cases by Continent
Read in all the csv files per continent.
```{r}
africa = read.csv("refined_data_Africa.csv")
asia = read.csv("refined_data_Asia.csv")
australia = read.csv("refined_data_Australia.csv")
europe = read.csv("refined_data_Europe.csv")
north_america = read.csv("refined_data_North_America.csv")
south_america = read.csv("refined_data_South_America.csv")
```

Total number of confirmed cases per continent calculated 
```{r}
africa_total_cases = sum(africa$Total.Confirmed.Cases)
asia_total_cases = sum(asia$Total.Confirmed.Cases)
australia_total_cases = sum(australia$Total.Confirmed.Cases)
europe_total_cases = sum(europe$Total.Confirmed.Cases)
na_total_cases = sum(north_america$Total.Confirmed.Cases)
sa_total_cases = sum(south_america$Total.Confirmed.Cases)
total_cases_sum = africa_total_cases + asia_total_cases + australia_total_cases + europe_total_cases + na_total_cases + sa_total_cases
```

Plotted the total counts of the confirmed cases
```{r}
total_cases = c(africa_total_cases/total_cases_sum, asia_total_cases/total_cases_sum, australia_total_cases/total_cases_sum, europe_total_cases/total_cases_sum, na_total_cases/total_cases_sum, sa_total_cases/total_cases_sum)
continents = c("Africa", "Asia", "Australia", "Europe", "NA", "SA")
barplot(total_cases, main="Relative Frequency of Total Confirmed Cases by Continent",names.arg=continents, ylim=c(0,0.3))
```

# Data Visualization: Change in Activeness Rates by Continent


